[package]
name = "ytd-video-downloader"
version = "0.1.0"
authors = ["Michael Howard <michael.howard.h@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threadpool = "1.7.1"
